### ISSUE TITLE
Delete Parcel From Project - In Row

### ISSUE THREAD

**Issue by jakebanderson321** [anderson-optimization/frontend-documentation#18]
### Feature Request
Instead of having the delete parcel from project be underneath the parcel list have it setup to be a right click and delete. This way users don't have to navigate off the list and can easily do it without interrupting their parcel rating flow.

**Comment by eanderson4** [comment]
Just a fyi on how I was speccing out functionality like this.  Instead of a right click, I was going to add buttons next to the name when the summary was open.  So for example, when the user clicks a row (or double clicks in a table with multi-row select enabled like projects), the summary opens and some buttons would appear next to the name link.  One of these optional buttons would be a trash bin, so on the project page it would be bound to a function that removes it from the project.  On the asset page, we could optionally bind to delete an asset, etc.  When not bound, the button would be hiddne

the property that defines whether a summary is open is called extraRow on the data object.   There is a cell renderer that is responsible for rendering the name column

**Comment by eanderson4** [comment]
This has been deemed low prioritization and removed from latest release.
